
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'ALIAS AND ANDAND ARROW BANG BEGIN_S BEGIN_U BREAK B_AND B_LEFT_SHIFT B_ONES B_OR B_RIGHT_SHIFT B_XOR CASE CLASS CLASS_VAR CMP COLON COMMA COMPLEX CONSTANT DEF DEFINEDQ DIV DIVEQLS DO DOT ELSE ELSIF ENCODING END_S END_U ENSURE EQ EQLS EQQ FALSE FILE FLOAT FOR GE GLOBAL_VAR GT IF IN INSTANCE_VAR INTEGER INTERPOLATION LBRACE LBRACKET LE LINE LOCAL_VAR LPAREN LT MATCH MINUS MINUSEQLS MOD MODEQLS MODULE MULT MULTEQLS NE NEXT NIL NMATCH NOT OR OROR PLUS PLUSEQLS POWER POWEREQLS PRINT PUTS QUESTION RANGE_EXCL RANGE_INCL RATIONAL RBRACE RBRACKET REDO REGEXP RESCUE RETRY RETURN RPAREN SELF SEMICOLON STR SUPER SYMBOL THEN TRUE UNDEF UNLESS UNTIL WHEN WHILE YIELDexpresion : valor PLUS valorvalor : INTEGERvalor : LOCAL_VAR'
    
_lr_action_items = {'INTEGER':([0,5,],[3,3,]),'LOCAL_VAR':([0,5,],[4,4,]),'$end':([1,3,4,6,],[0,-2,-3,-1,]),'PLUS':([2,3,4,],[5,-2,-3,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'expresion':([0,],[1,]),'valor':([0,5,],[2,6,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> expresion","S'",1,None,None,None),
  ('expresion -> valor PLUS valor','expresion',3,'p_expresion_suma','main.py',5),
  ('valor -> INTEGER','valor',1,'p_valor_numero','main.py',10),
  ('valor -> LOCAL_VAR','valor',1,'p_valor_variable','main.py',14),
]
